server:
    port: 8081

logging:
    level:
        tk.mybatis: INFO
spring:
    datasource:
#        # 使用druid数据源
        name: soho_prd_finance
        url: jdbc:mysql://192.168.220.**:3306/soho_prd_finance?useUnicode=true&amp;characterEncoding=UTF-8
        username: pccw
        password: pccw
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: false
        minEvictableIdleTimeMillis: 300000
    freemarker:
        cache: false
        request-context-attribute: request